baseURL = "https://bunreal.github.io/blog/"
languageCode = "en-us"
title = "bComingB"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "bComingB"
description = "This is the website of Bunreal, and I made this for myself and others."
author = "Bunreal"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
disableSpecial1stPost = false
comments = true
hidemeta = false
showtoc = true
tocopen = false
ShowBreadCrumbs = true
ShowPostNavLinks= true


  [params.assets]
  favicon = "bun.png"
  favicon16x16 = "bun.png"
  favicon32x32 = "bun.png"
  apple_touch_icon = "bun.png"
  safari_pinned_tab = "bun.png"

  [params.label]
  text = "bComingB"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Hi, I'm Bunreal ğŸ‘‹"
  subtitle = "æˆ‘æ˜¯å°ä¸­äººï¼Œç¾åœ¨æ˜¯ç§»å‹•å¿ƒç†å¸«ï¼Œæœ‰åœ¨å­¸æ ¡å­¸è¼”ä¸­å¿ƒå…¼è·ï¼Œä¹Ÿæœ‰åœ¨æ–°åŒ—çš„æ²»ç™‚æ‰€æ¥æ¡ˆï¼Œå¯«è‡ªå·±è¦ºå¾—é‡è¦çš„æˆ–æ˜¯å–œæ­¡çš„äº‹"
  imageUrl = "https://lh3.googleusercontent.com/4kYwhVOLvEvAUUm_fY_2AkA7emRBzHf8PgaXPpif1GKDmnECaUZB7RXHiJmtHAaDM9EjZqjnjEUpm1apk-sq4xtf6uk8mnG1XG_DLtKtviASWf1RyWHYzT1Q9nUsaLkrRAZEKBViAS-X0D7XEhxEXwnWrh9vtw6jjmM__WBCeGsow7QGRlPmW8nT9eiUKohtsr-0dG3F3zaVqWjMlnoRSDzAH7qifbvYsrfOlAL9h6Yobg4_97HtIktGXBuSMDXyMA5Aix-VEYjX4lsrF4WNI1EqTzKbjKLZGvx2gg3Mv7qrJ9bfpQTbT-uM5WPTTJEgASdR900tADv7Vtn54AbeZVvg9IzBuDk3tvW2fR0N6Z-gBN5Qp9hN8l7UIupBEx3eeCJ8SKAfbYgtVg6u1uMZ4VkvbJ-dz5HDvpt0qVDRk_TGZrcNo8AgoWDnHC_0c05IsxjdS418yz-UUCeFDZie07GOhMlsR8MlQ-cm0EsEZ3gq5eE942Xmp4JItLXp7sBV1pJNvugVHOe3sxFohALt7XnaJYRzo6RDmpVFLXuXRHDuvPic8S0vzBrTEaWxSrBtxDNO995pOMcnfvwDpJeBA_H47MFswX7KbUgP7p3BM2dr5zM9sN-LzRAFyI36j9s2G-7qJEue7UDe6xIqrXheahbGtHWBFUzgiPlE4E-d6BtfchmgsDTa44_RfLWgLc_iXWzWpBf8-tQFJjcLINiADSMu2sThBl_SCdoDUAIq4JmLf77kOWZjdKfJi-XKrKgp9wR5kyS69WvjamjrHXTpVr-pt9Eq1gXZdjts7qFEsDoOz8hpZVyrmHBEEO-CNnSoBvddRW4YWf1NQczaiQH3ApPUsMq8xyTrn9hPlWamkOrATXoH5n0xjEx9dudR0qyfdIIc6SQz6vGwxwaPpMAaJBwhvRf2zQOgx_axJLcM5a7Xzg=w1846-h1231-no?authuser=0"
  imageWidth = 200
  imageHeight = 200
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "æ–‡ç« "
    url = "posts"

    [[params.profileMode.buttons]]
    name = "æ¨™ç±¤"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi, I'm Bunreal ğŸ‘‹"
  Content = "å°ä¸­äººï¼Œç¾åœ¨æ˜¯ç§»å‹•å¿ƒç†å¸«ï¼Œæœ‰åœ¨å­¸æ ¡å­¸è¼”ä¸­å¿ƒå…¼è·ï¼Œä¹Ÿæœ‰åœ¨æ–°åŒ—çš„æ²»ç™‚æ‰€æ¥æ¡ˆï¼Œå¯«è‡ªå·±è¦ºå¾—é‡è¦çš„æˆ–æ˜¯å–œæ­¡çš„äº‹"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/bunreal.young"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/bunrealy/"

  [[params.socialIcons]]
  name = "medium"
  url = ""

  [[params.socialIcons]]
  name = "email"
  url = "mailto:bunreal0@gmail.com?Subject=æ–°å¹´å¿«æ¨‚"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "é—œæ–¼é€™è£¡"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "æ–‡ç« å½™æ•´"
url = "/archives/"
weight = 4

[[menu.main]]
identifier = "categories"
name = "åˆ†é¡"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "æ¨™ç±¤"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "find"
name = "æƒ³è¦å¿ƒç†è«®å•†"
url = "/find/"
weight = 10

[[menu.main]]
identifier = "search"
name = "æœå°‹"
url = "/search/"
weight = 5


