baseURL = "https://bunreal.github.io/blog/"
languageCode = "en-us"
title = "bComingB"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
author = "Bunreal"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
disableSpecial1stPost = false
comments = true
hidemeta = false
showtoc = true
tocopen = false
ShowBreadCrumbs = true
ShowPostNavLinks= true


  [params.assets]
  favicon = "bun.png"
  favicon16x16 = "bun.png"
  favicon32x32 = "bun.png"
  apple_touch_icon = "bun.png"
  safari_pinned_tab = "bun.png"

  [params.label]
  text = "bComingB"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "ä½œè€…ç°¡ä»‹"
  subtitle = "æ¥Šæ·¯æƒ‡"
  imageUrl = "https://lh3.googleusercontent.com/cD1h_6M8YuGMiwjpRfZcZvthjvr0a_APM9AZdGIEwCPMq5xCDqSQ5Nw9P0xZj3KVMD6fEaCax07tq07PW7vAxMrLUXqm_YA5FKHXNRXAxr-9302kU6yMs_SB-gz5eVxJ4gid4WgcOZByY9yaRmZtj3Ubd6ZklHPsrUq6oRL8i4ujEMxpb5A_G4nEwb14NQ4qyY54IRBAlh8tH1z3m64rxu-Jb9X5nORpAbvSsKTjdMQi4ocxnp0b3s07Nh3rpXb3bAMQ1Tia8IXBimqye-1ssJlP9xdPy60XSM5o5bDhhs7MyChdJrHs9YRsc8y4OyAiaNxVjau9c64ythx77CdWcydzhN5zkjpIAYSasRbzS1y-GljbST8oOwYu8RWMcDliwQGHElhlTn4FNGsoYgn78GRnNt7WTqb6MXIGOR9oggAiz0RQeH01Z9vt6MMV8pd6leUhQZWa0yvanNrAji5IbxdjTx2cKcKzx1N8hh-TaSSxBEbh46lVyq4LjMHG7StuMf_5rgKOxadui7vpJCk4IJP-TTm5qS-zNiEf8s_SoI4-3cpPfRW6rTVQkz4h2ftVnIlEtv3XgxqgbU9DwthnskxbbInLT6-AezNSBMAKe6O36MWE6J-LXJm367_UaQmfc8U9Scjl2sMo4Ey4bi5ZWr0WFiH9Y-yzOIwWpsfY0tg3ARH6R0ZvSgGMvnPOQaIOymnhc2oQKOP8rQ6UclgJUuKXw1C3Z7TFci70sPj8XErflkAdrdGxcJ0_-GN6SSmt3KO7FoBgMKgUfvUt3OJqIRLScmwyHjFual1TI511tpVs_wxhQJcjo2QH6v4p7HmtAQk-2vW7hx7n-96lGeIHIVse89j51N4Gkl62Mmo4m-UKq2Kl4M0FRkO2ODTzqcFgnvWzg7zKq1KflP8tex3DR86c1m83oAmAUXujGfMkTDYJfA=w1478-h1108-no?authuser=0"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi, I'm Bunreal ğŸ‘‹"
  Content = "å°ä¸­äººï¼Œç¾åœ¨æ˜¯ç§»å‹•å¿ƒç†å¸«ï¼Œæœ‰åœ¨å­¸æ ¡å­¸è¼”ä¸­å¿ƒå…¼è·ï¼Œä¹Ÿæœ‰åœ¨æ–°åŒ—çš„æ²»ç™‚æ‰€æ¥æ¡ˆï¼Œå¯«è‡ªå·±è¦ºå¾—é‡è¦çš„æˆ–æ˜¯å–œæ­¡çš„äº‹"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/bunreal.young"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/bunrealy/"

  [[params.socialIcons]]
  name = "medium"
  url = ""

  [[params.socialIcons]]
  name = "email"
  url = "mailto:bunreal0@gmail.com?Subject=æ–°å¹´å¿«æ¨‚"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "profile"
name = "Profile"
url = "/profile/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20


