baseURL = "https://bunreal.github.io/blog/"
languageCode = "en-us"
title = "bComingB"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
author = "Bunreal"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
disableSpecial1stPost = false
comments = true
hidemeta = false
showtoc = true
tocopen = false
ShowBreadCrumbs = true
ShowPostNavLinks= true


  [params.assets]
  favicon = "bun.png"
  favicon16x16 = "bun.png"
  favicon32x32 = "bun.png"
  apple_touch_icon = "bun.png"
  safari_pinned_tab = "bun.png"

  [params.label]
  text = "bComingB"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi, I'm Bunreal ğŸ‘‹"
  Content = "å°ä¸­äººï¼Œç¾åœ¨æ˜¯ç§»å‹•å¿ƒç†å¸«ï¼Œæœ‰åœ¨å­¸æ ¡å­¸è¼”ä¸­å¿ƒå…¼è·ï¼Œä¹Ÿæœ‰åœ¨æ–°åŒ—çš„æ²»ç™‚æ‰€æ¥æ¡ˆï¼Œå¯«è‡ªå·±è¦ºå¾—é‡è¦çš„æˆ–æ˜¯å–œæ­¡çš„äº‹"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/bunreal.young"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/bunrealy/"

  [[params.socialIcons]]
  name = "medium"
  url = ""

  [[params.socialIcons]]
  name = "email"
  url = "mailto:bunreal0@gmail.com?Subject=æ–°å¹´å¿«æ¨‚"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20


