baseURL = "https://bunreal.github.io/blog/"
languageCode = "en-us"
title = "bComingB"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "bComingB"
description = "This is the website of Bunreal, and I made this for myself and others."
author = "Bunreal"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
disableSpecial1stPost = false
comments = true
hidemeta = false
showtoc = true
tocopen = false
ShowBreadCrumbs = true
ShowPostNavLinks= true


  [params.assets]
  favicon = "bun.png"
  favicon16x16 = "bun.png"
  favicon32x32 = "bun.png"
  apple_touch_icon = "bun.png"
  safari_pinned_tab = "bun.png"

  [params.label]
  text = "bComingB"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Hi, I'm Bunreal ğŸ‘‹"
  subtitle = "æˆ‘æ˜¯å°ä¸­äººï¼Œç¾åœ¨æ˜¯ç§»å‹•å¿ƒç†å¸«ï¼Œæœ‰åœ¨å­¸æ ¡å­¸è¼”ä¸­å¿ƒå…¼è·ï¼Œä¹Ÿæœ‰åœ¨æ–°åŒ—çš„æ²»ç™‚æ‰€æ¥æ¡ˆï¼Œå¯«è‡ªå·±è¦ºå¾—é‡è¦çš„æˆ–æ˜¯å–œæ­¡çš„äº‹"
  imageUrl = "images/profile.jpeg"
  imageWidth = 200
  imageHeight = 200
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "æ–‡ç« "
    url = "posts"

    [[params.profileMode.buttons]]
    name = "æ¨™ç±¤"
    url = "tags"

    [[params.profileMode.buttons]]
    name = "åˆ†é¡"
    url = "categories"
    weight = 2

  [params.homeInfoParams]
  Title = "Hi, I'm Bunreal ğŸ‘‹"
  Content = "å°ä¸­äººï¼Œç¾åœ¨æ˜¯ç§»å‹•å¿ƒç†å¸«ï¼Œæœ‰åœ¨å­¸æ ¡å­¸è¼”ä¸­å¿ƒå…¼è·ï¼Œä¹Ÿæœ‰åœ¨æ–°åŒ—çš„æ²»ç™‚æ‰€æ¥æ¡ˆï¼Œå¯«è‡ªå·±è¦ºå¾—é‡è¦çš„æˆ–æ˜¯å–œæ­¡çš„äº‹"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/bunreal.young"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/bunrealy/"

  [[params.socialIcons]]
  name = "medium"
  url = ""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Bunreal"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:bunreal0@gmail.com?Subject=æ–°å¹´å¿«æ¨‚ï¼Œæˆ‘æƒ³è¦èˆ‡ä½ è¯ç¹«"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "é—œæ–¼é€™è£¡"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "æ–‡ç« å½™æ•´"
url = "/archives/"
weight = 4

[[menu.main]]
identifier = "find"
name = "è¯çµ¡æˆ‘"
url = "/find/"
weight = 10

[[menu.main]]
identifier = "search"
name = "æœå°‹"
url = "/search/"
weight = 5


